"""dd

Revision ID: 38301cc3065f
Revises: ae78e4660058
Create Date: 2025-09-12 17:59:48.032243

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38301cc3065f'
down_revision: Union[str, Sequence[str], None] = 'ae78e4660058'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('attack_type', sa.Enum('no_attack', 'blur', 'noise', 'adversarial', 'other', name='attack_type_enum'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('images', 'attack_type')
    # ### end Alembic commands ###
