"""initial

Revision ID: 4228895e9d33
Revises: 3838308bf1cc
Create Date: 2025-09-11 11:56:50.450777

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4228895e9d33'
down_revision: Union[str, Sequence[str], None] = '3838308bf1cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('annotations', sa.Column('coordinates', sa.ARRAY(sa.Integer()), nullable=False))
    op.drop_column('annotations', 'height')
    op.drop_column('annotations', 'width')
    op.drop_column('annotations', 'y')
    op.drop_column('annotations', 'x')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('annotations', sa.Column('x', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('annotations', sa.Column('y', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('annotations', sa.Column('width', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('annotations', sa.Column('height', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('annotations', 'coordinates')
    # ### end Alembic commands ###
