"""dd

Revision ID: ae78e4660058
Revises: 698bded75e89
Create Date: 2025-09-11 21:37:47.802555

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae78e4660058'
down_revision: Union[str, Sequence[str], None] = '698bded75e89'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('experiments',
    sa.Column('experiment_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_date', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False),
    sa.PrimaryKeyConstraint('experiment_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('runs',
    sa.Column('run_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('experiment_id', sa.Integer(), nullable=False),
    sa.Column('run_date', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('accuracy', sa.Float(), nullable=True),
    sa.Column('flagged', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.experiment_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('run_id')
    )
    op.create_table('images',
    sa.Column('image_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('original_name', sa.String(length=255), nullable=True),
    #sa.Column('attack_type', sa.Enum('no_attack', 'blur', 'noise', 'adversarial', 'other', name='attack_type_enum'), nullable=False),
    sa.Column('added_date', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('coordinates', sa.ARRAY(sa.Integer(), dimensions=1), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['runs.run_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('image_id'),
    sa.UniqueConstraint('file_path')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('images')
    op.drop_table('runs')
    op.drop_table('experiments')
    # ### end Alembic commands ###
